# Application
spring.application.name=coffee-and-co

# PostgreSQL Database (Render)
spring.datasource.url=jdbc:postgresql://dpg-d9d1spd7vvec73emcfhg-a.oregon-postgres.render.com:5432/coffee_co
spring.datasource.username=root
spring.datasource.password=MTo4z1aemgyBvpmgi2X9ixJ7f9CdV40Q
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Server
server.port=8080